---   
  - name: Install docker-py
    yum: name=docker-python
       
  - name: Install docker
    yum: name=docker state=present
    
  - name: Stopping Docker
    service: name=docker state=stopped  
    
  - name: Remove docker selinux config
    replace: dest=/etc/sysconfig/docker regexp="^OPTIONS='--selinux-enabled'" replace="OPTIONS=" backup=no
    
  - name: Starting Docker
    service: name=docker state=started
    
  - name: Enabling Docker to start at boot
    service: name=docker enabled=yes 