---   
  - name: Run mongo
    docker: image=mongo:2.4.14 name=mongo ports=27017 command="--noprealloc --smallfiles"
    
  - name: Pre-load the collection
    shell: mongorestore --drop --collection fda_enforcement --db dbname dbname/fda_enforcement.bson
    ignore_errors: true
   