# -*- mode: ruby -*-
# vi: set ft=ruby :

# The v_centos is a directory that contain Vagrant config files to spin up Virtual Machines, Centos, 
# using VirtualBox & Vagrant locally to test building container images from this project.  To use them, after
# you have both VirtualBox 4.3.12 r93733 and Vagrant 1.7.1 installed, simply from a CMD prompt, run 

# vagrant up


# The provisioned VM will have all the necessary components to be able to test out the building of this prototype's 
# code base as well as the  docker containers either manually via the docker build or through the Maven build


# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "chef/centos-7.0"
  #config.vm.box = "relativkreativ/centos-7-minimal"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 80

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.  
  config.vm.synced_folder "../../../../../", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb| 
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end
	$script = <<SCRIPT
	
	yum -y install epel-release
	
	yum -y install wget docker java-1.7.0-openjdk-devel
	
	wget -O ~/apache-maven-3.3.3-bin.tar.gz "http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz"
	tar -C /usr/local -xzf ~/apache-maven-3.3.3-bin.tar.gz
	echo 'export PATH=$PATH:/usr/local/apache-maven-3.3.3/bin' > /etc/profile.d/maven.sh
	rm ~/apache-maven-3.3.3-bin.tar.gz
	chmod +x /etc/profile.d/maven.sh
	service docker restart
	
	echo -e '[mongodb-org-3.0]\nname=MongoDB Repository\nbaseurl=https://repo.mongodb.org/yum/redhat/7/mongodb-org/3.0/x86_64/\ngpgcheck=0\nenabled=1' | tee /etc/yum.repos.d/mongodb-org-3.0.repo
	yum -y install mongodb-org
	
	semanage port -a -t mongod_port_t -p tcp 27017
	
	service mongod start
	
	echo 'Done provisioning vm.  Use it.'
SCRIPT
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell",
     inline: $script   
end
