# Dockerfile for building a image containing the components for the prototype.

FROM centos:7.1.1503

RUN echo -e "[mongodb] \nname=mongodb-org-3.0\nbaseurl=http://repo.mongodb.org/yum/redhat/7/mongodb-org/3.0/x86_64/\ngpgcheck=0\nenabled=1" | tee /etc/yum.repos.d/mongodb-org-3.0.repo

RUN yum -y install mongodb-org

RUN mkdir -p /mnt/rdafs

# Expose port 27017 from the container to the host
EXPOSE 27017 28017

# Set usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT usr/bin/mongod --dbpath /mnt/rdafs -rest --noprealloc --smallfiles